# Generated by Django 4.0.3 on 2022-04-05 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.IntegerField(blank=True, choices=[(1, 'POC'), (2, 'PO'), (3, 'ECIF'), (4, 'DEMO'), (4, 'Initiative'), (4, 'Development')], default=1, null=True),
        ),
    ]
