# Generated by Django 4.0.3 on 2022-04-05 07:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Project_Management', '0004_remove_project_vertical_project_vertical'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectteam',
            name='team',
        ),
        migrations.AddField(
            model_name='projectteam',
            name='team',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
