# Generated by Django 4.0.3 on 2022-04-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Management', '0005_remove_projectteam_team_projectteam_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.IntegerField(blank=True, choices=[(1, 'POC'), (2, 'PO'), (3, 'ECIF'), (4, 'DEMO'), (5, 'Initiative'), (6, 'Development')], default=1, null=True),
        ),
    ]
