# Generated by Django 4.0.3 on 2022-04-09 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Project_Management', '0007_alter_task_effort_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectteam',
            name='team',
        ),
        migrations.AddField(
            model_name='projectteam',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='effort_hours',
            field=models.IntegerField(),
        ),
    ]
