# Generated by Django 4.0.3 on 2022-04-15 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Project_Management', '0011_teammember_m2'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='m3',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='m3', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammember',
            name='m4',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='m4', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
