# Generated by Django 4.0.3 on 2022-04-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Management', '0015_alter_teammember_m2_alter_teammember_m3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('comments', models.TextField(max_length=500)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
