# Generated by Django 4.0.3 on 2022-04-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project_Management', '0016_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comments',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
