# Generated by Django 4.0.3 on 2022-04-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_userrole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='userrole',
            field=models.IntegerField(choices=[(1, 'Admin'), (2, 'Manager'), (3, 'Executive'), (4, 'User'), (5, 'CsOwner'), (6, 'Demo')], default=4),
        ),
    ]
